use master 
GO
Create database COMERCIO_DB
GO
use COMERCIO_DB
GO
Create Table LOCALIDADES(
CODIGO_POSTAL INT NOT NULL PRIMARY KEY,
LOCALIDADES VARCHAR(100) NOT NULL 
)
GO
Create Table CLIENTES(
  DNI VARCHAR(10) NOT NULL PRIMARY KEY,
  APELLIDO VARCHAR(50) NULL,
  NOMBRE VARCHAR(50) NOT NULL,
  TELEFONO VARCHAR(15) NULL,
  MAIL VARCHAR(50) NULL,
  DIRECCION VARCHAR(50) NULL,
  CODPOSTAL INT NOT NULL FOREIGN KEY REFERENCES LOCALIDADES(CODIGO_POSTAL)
)

GO
Create Table PROVEEDORES(
  CUIT VARCHAR(12) NOT NULL PRIMARY KEY,
  APELLIDO VARCHAR(50) NULL,
  NOMBRE_PROVEEDOR VARCHAR(50) NOT NULL,
  TELEFONO VARCHAR(15) NULL,
  MAIL VARCHAR(50) NULL,
  DIRECCION VARCHAR(50) NULL,
  CODPOSTAL INT NOT NULL FOREIGN KEY REFERENCES LOCALIDADES(CODIGO_POSTAL)
)
GO
Create Table MARCAS(
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
DESCRIPCION_MARCA VARCHAR(100) NOT NULL
)
GO
Create Table CATEGORIAS(
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
DESCRIPCION_CATEGORIA VARCHAR(200) NOT NULL
)
GO
CREATE TABLE PRODUCTOS(
  CODIGO VARCHAR(10) NOT NULL PRIMARY KEY,
  NOMBRE VARCHAR(50) NOT NULL,
  IDMARCA INT NULL FOREIGN KEY REFERENCES MARCAS(ID),
  IDCATEGORIA INT NOT NULL FOREIGN KEY REFERENCES CATEGORIAS(ID),
  CUITPROVEEDOR VARCHAR(12) NOT NULL FOREIGN KEY REFERENCES PROVEEDORES(CUIT),
  PRECIO MONEY NOT NULL,
  STOCK_ACTUAL DECIMAL NOT NULL,
  STOCK_MINIMO DECIMAL NOT NULL,
  PORCENTAJE_GAN DECIMAL NOT NULL,
  ACTIVO BIT
)
GO
CREATE TABLE VENTAS(
  NUM_VENTA INT NOT NULL PRIMARY KEY,
  COD_CLIENTE VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES CLIENTES(DNI),
  FECHA DATETIME NOT NULL,
  TOTAL MONEY NOT NULL,
  TIPO_DOC CHAR NOT NULL
)
GO
CREATE TABLE DETALLE_VENTA(
  NUM_DETALLE INT NOT NULL PRIMARY KEY,
  NUM_VENTA INT NOT NULL FOREIGN KEY REFERENCES VENTAS(NUM_VENTA),
  COD_PRODUCTO VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES PRODUCTOS(CODIGO),
  CANTIDAD INT NOT NULL,
  PRECIO_VENTA MONEY NOT NULL,
  DESCUENTO MONEY NULL,
  SUBTOTAL MONEY NOT NULL,
  OBSERVACIONES VARCHAR (300) NULL,
  CONDICION_PAGO VARCHAR (100) NOT NULL
)
GO
CREATE TABLE COMPRAS(
  NUM_COMPRA INT NOT NULL PRIMARY KEY,
  COD_PROVEEDOR VARCHAR(12) NOT NULL FOREIGN KEY REFERENCES PROVEEDORES(CUIT),
  TOTAL MONEY NOT NULL,
  FECHA DATETIME NOT NULL,
  TIPO_DOC CHAR NOT NULL
)
GO
CREATE TABLE DETALLE_COMPRA(
  NUM_DETALLE INT NOT NULL PRIMARY KEY,
  NUM_COMPRA INT NOT NULL FOREIGN KEY REFERENCES COMPRAS(NUM_COMPRA),
  COD_PRODUCTO VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES PRODUCTOS(CODIGO),
  CANTIDAD INT NOT NULL,
  PRECIO_COMPRA MONEY NOT NULL,
  DESCUENTO MONEY NULL,
  SUBTOTAL MONEY NOT NULL,
  OBSERVACIONES VARCHAR (300) NULL,
  CONDICION_PAGO VARCHAR (100) NOT NULL
)
GO
CREATE TABLE USUARIOS(
 ID_USUARIO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
 NOMBRE VARCHAR(100) NOT NULL,
 CONTRASEÑA VARCHAR(100) NOT NULL,
 TIPO_USUARIO VARCHAR(100) NOT NULL
)
GO
/*
CREATE TABLE VENTAS_X_CLIENTE(
  NUM_VENTA INT NOT NULL FOREIGN KEY REFERENCES VENTAS (NUM_VENTA),
  DNI_CLIENTE VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES CLIENTES (DNI),
  IMPORTE MONEY NOT NULL,
  PRIMARY KEY (NUM_VENTA, DNI_CLIENTE)
)
GO
*/
/*
CREATE TABLE COMPRAS_X_PROVEEDOR(
  NUM_COMPRA INT NOT NULL FOREIGN KEY REFERENCES COMPRAS (NUM_COMPRA),
  CUIT_PROVEEDOR VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES PROVEEDORES (CUIT),
  IMPORTE MONEY NOT NULL,
  PRIMARY KEY (NUM_COMPRA, CUIT_PROVEEDOR)
)
GO
*/
/*
CREATE TABLE PRODUCTOS_X_PROVEEDOR(
  CODIGO_PRODUCTO VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES PRODUCTOS (CODIGO),
  CUIT_PROVEEDOR VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES PROVEEDORES (CUIT),
  PRIMARY KEY (CODIGO_PRODUCTO, CUIT_PROVEEDOR)
)
*/