--MARCAS
INSERT INTO MARCAS (DESCRIPCION) VALUES ('MAROLIO')
INSERT INTO MARCAS (DESCRIPCION) VALUES ('RHODESIA')
INSERT INTO MARCAS (DESCRIPCION) VALUES ('MOGUL')
INSERT INTO MARCAS (DESCRIPCION) VALUES ('MILKA')
INSERT INTO MARCAS (DESCRIPCION) VALUES ('ROCKLETS')
INSERT INTO MARCAS (DESCRIPCION) VALUES ('GUAYMALLEN')
INSERT INTO MARCAS (DESCRIPCION) VALUES ('OREO')

--CATEGORIAS
INSERT INTO CATEGORIAS (DESCRIPCION) VALUES ('CHOCOLATES')
INSERT INTO CATEGORIAS (DESCRIPCION) VALUES ('GOMITAS')
INSERT INTO CATEGORIAS (DESCRIPCION) VALUES ('ALFAJORES')
INSERT INTO CATEGORIAS (DESCRIPCION) VALUES ('BEBIDAS')
INSERT INTO CATEGORIAS (DESCRIPCION) VALUES ('CARAMELOS')

--LOCALIDADES
INSERT INTO LOCALIDADES (CODIGO_POSTAL,LOCALIDADES) VALUES (1620,'Flores')
INSERT INTO LOCALIDADES (CODIGO_POSTAL,LOCALIDADES) VALUES (1621,'Palermo')
INSERT INTO LOCALIDADES (CODIGO_POSTAL,LOCALIDADES) VALUES (1622,'Ciudadela')

--PROVEEDORES
INSERT INTO PROVEEDORES (CUIT,NOMBRE,TELEFONO,MAIL,DIRECCION,CODPOSTAL) 
VALUES ('2050309453','SUPERGOMITAS SRL','1150602232','contacto@supergomitas.com','Centenario 126',1620)
INSERT INTO PROVEEDORES (CUIT,NOMBRE,TELEFONO,MAIL,DIRECCION,CODPOSTAL) 
VALUES ('1565822321','MILKA SA','1185213546','contacto@milka.com','Lavalle 2456',1621)
INSERT INTO PROVEEDORES (CUIT,NOMBRE,TELEFONO,MAIL,DIRECCION,CODPOSTAL) 
VALUES ('2213236255','ARCOR','1144203220','hola@arcor.com','Av Siempreviva 123',1622)

--CLIENTES
INSERT INTO CLIENTES (DNI,APELLIDO,NOMBRE,TELEFONO,MAIL,DIRECCION,CODPOSTAL) 
VALUES ('40206350','CASTAÑO','MARCELO','1150327888','marcelocastaño@outlook.com','Av Falcon 652',1622)
INSERT INTO CLIENTES (DNI,APELLIDO,NOMBRE,TELEFONO,MAIL,DIRECCION,CODPOSTAL) 
VALUES ('32875989','GOMEZ','YESICA','348474777','yesicagomez@outlook.com','Pringles 1225',1621)
INSERT INTO CLIENTES (DNI,APELLIDO,NOMBRE,TELEFONO,MAIL,DIRECCION,CODPOSTAL) 
VALUES ('40889566','DIAZ','MONICA','1130057599','monidiaz@gmail.com','Colon 442',1621)
INSERT INTO CLIENTES (DNI,APELLIDO,NOMBRE,TELEFONO,MAIL,DIRECCION,CODPOSTAL) 
VALUES ('25192577','SANCHEZ','ALBERTO','1140427364','','Libertad 3298',1620)
INSERT INTO CLIENTES (DNI,APELLIDO,NOMBRE,TELEFONO,MAIL,DIRECCION,CODPOSTAL) 
VALUES ('36542564','GALLARDO','ALEX','1187980011','soyalex@gmail.com','Lamberti 987',1620)

--USUARIOS
INSERT INTO USUARIOS(NOMBRE,CONTRASEÑA,TIPO_USUARIO) 
VALUES ('EZEQUIEL','1996','VENDEDOR')
INSERT INTO USUARIOS(NOMBRE,CONTRASEÑA,TIPO_USUARIO) 
VALUES ('ADMIN','PROGRAMACION','ADMIN')

--PRODUCTOS
--COMPRAS
--VENTAS