use COMERCIO_DB 
--MARCAS
INSERT INTO MARCAS (DESCRIPCION_MARCA,ACTIVO) VALUES ('MILKA',1)
INSERT INTO MARCAS (DESCRIPCION_MARCA,ACTIVO) VALUES ('OREO',1)
INSERT INTO MARCAS (DESCRIPCION_MARCA,ACTIVO) VALUES ('ARCOR',1)
INSERT INTO MARCAS (DESCRIPCION_MARCA,ACTIVO) VALUES ('TERRABUSI',1)
INSERT INTO MARCAS (DESCRIPCION_MARCA,ACTIVO) VALUES ('BAGLEY',1)

--CATEGORIAS
INSERT INTO CATEGORIAS (DESCRIPCION_CATEGORIA,ACTIVO) VALUES ('CHOCOLATES',1)
INSERT INTO CATEGORIAS (DESCRIPCION_CATEGORIA,ACTIVO) VALUES ('GOMITAS',1)
INSERT INTO CATEGORIAS (DESCRIPCION_CATEGORIA,ACTIVO) VALUES ('ALFAJORES',1)
INSERT INTO CATEGORIAS (DESCRIPCION_CATEGORIA,ACTIVO) VALUES ('BEBIDAS',1)
INSERT INTO CATEGORIAS (DESCRIPCION_CATEGORIA,ACTIVO) VALUES ('CARAMELOS',1)
INSERT INTO CATEGORIAS (DESCRIPCION_CATEGORIA,ACTIVO) VALUES ('GALLETITAS',1)

--LOCALIDADES
--INSERT INTO LOCALIDADES (CODIGO_POSTAL,LOCALIDADES) VALUES (1620,'Flores')
--INSERT INTO LOCALIDADES (CODIGO_POSTAL,LOCALIDADES) VALUES (1621,'Palermo')
--INSERT INTO LOCALIDADES (CODIGO_POSTAL,LOCALIDADES) VALUES (1622,'Ciudadela')

--PROVEEDORES
INSERT INTO PROVEEDORES (CUIT,NOMBRE_PROVEEDOR,TELEFONO,MAIL,DIRECCION,ACTIVO) 
VALUES ('2050309453','OREO SRL','1150602232','contacto@oreo.com','Centenario 126',1)
INSERT INTO PROVEEDORES (CUIT,NOMBRE_PROVEEDOR,TELEFONO,MAIL,DIRECCION,ACTIVO) 
VALUES ('1565822321','MILKA SA','1185213546','contacto@milka.com','Lavalle 2456',1)
INSERT INTO PROVEEDORES (CUIT,NOMBRE_PROVEEDOR,TELEFONO,MAIL,DIRECCION,ACTIVO) 
VALUES ('2213236255','ARCOR SA','1144203220','hola@arcor.com','Av Siempreviva 123',1)
INSERT INTO PROVEEDORES (CUIT,NOMBRE_PROVEEDOR,TELEFONO,MAIL,DIRECCION,ACTIVO) 
VALUES ('3013236285','COCA-COLA SA','1144203220','hola@cocacola.com','La Rioja 2982',1)

--CLIENTES
INSERT INTO CLIENTES (DNI,APELLIDO,NOMBRE,TELEFONO,MAIL,DIRECCION,ACTIVO) 
VALUES ('40206350','CASTAÑO','MARCELO','1150327888','marcelocastaño@outlook.com','Av Falcon 652',1)
INSERT INTO CLIENTES (DNI,APELLIDO,NOMBRE,TELEFONO,MAIL,DIRECCION,ACTIVO) 
VALUES ('32875989','GOMEZ','YESICA','348474777','yesicagomez@outlook.com','Pringles 1225',1)
INSERT INTO CLIENTES (DNI,APELLIDO,NOMBRE,TELEFONO,MAIL,DIRECCION,ACTIVO) 
VALUES ('40889566','DIAZ','MONICA','1130057599','monidiaz@gmail.com','Colon 442',1)
INSERT INTO CLIENTES (DNI,APELLIDO,NOMBRE,TELEFONO,MAIL,DIRECCION,ACTIVO) 
VALUES ('25192577','SANCHEZ','ALBERTO','1140427364','','Libertad 3298',1)
INSERT INTO CLIENTES (DNI,APELLIDO,NOMBRE,TELEFONO,MAIL,DIRECCION,ACTIVO) 
VALUES ('36542564','GALLARDO','ALEX','1187980011','soyalex@gmail.com','Lamberti 987',1)

--USUARIOS
INSERT INTO USUARIOS(MAIL,CONTRASEÑA,TIPO_USUARIO,ACTIVO) 
VALUES ('juancruzrey1@hotmail.com','vendedor',1,1)
INSERT INTO USUARIOS(MAIL,CONTRASEÑA,TIPO_USUARIO,ACTIVO) 
VALUES ('juancruzrey1@hotmail.com','admin',2,1)






--PRODUCTOS
INSERT INTO PRODUCTOS 
(CODIGO,NOMBRE,IDMARCA,IDCATEGORIA,PRECIO,PRECIO_VENTA,STOCK_ACTUAL,STOCK_MINIMO,PORCENTAJE_GAN,ACTIVO) 
VALUES ('1274','Guaymallen de Chocolate', 3, 3,50,0,110,40,45,1)

INSERT INTO PRODUCTOS 
(CODIGO,NOMBRE,IDMARCA,IDCATEGORIA,PRECIO,PRECIO_VENTA,STOCK_ACTUAL,STOCK_MINIMO,PORCENTAJE_GAN,ACTIVO) 
VALUES ('1275','Guaymallen de Leche', 3, 3,50,0,110,40,45,1)

INSERT INTO PRODUCTOS 
(CODIGO,NOMBRE,IDMARCA,IDCATEGORIA,PRECIO,PRECIO_VENTA,STOCK_ACTUAL,STOCK_MINIMO,PORCENTAJE_GAN,ACTIVO) 
VALUES ('1276','Guaymallen de Fruta', 3, 3,50,0,110,40,45,1)

INSERT INTO PRODUCTOS 
(CODIGO,NOMBRE,IDMARCA,IDCATEGORIA,PRECIO,PRECIO_VENTA,STOCK_ACTUAL,STOCK_MINIMO,PORCENTAJE_GAN,ACTIVO) 
VALUES ('1277','Mini Oreos', 2, 6,92,0,31,10,52,1)

INSERT INTO PRODUCTOS 
(CODIGO,NOMBRE,IDMARCA,IDCATEGORIA,PRECIO,PRECIO_VENTA,STOCK_ACTUAL,STOCK_MINIMO,PORCENTAJE_GAN,ACTIVO) 
VALUES ('1278','Gomitas Mogul', 3, 2,82,0,60,38,23,1)


--PROVEEDORES_x_PRODUCTO
--COMPRAS
--DETALLE_COMPRA
--VENTAS
--DETALLE_VENTA