use COMERCIO_DB 
--MARCAS
INSERT INTO MARCAS (DESCRIPCION_MARCA,ACTIVO) VALUES ('MAROLIO',1)
INSERT INTO MARCAS (DESCRIPCION_MARCA,ACTIVO) VALUES ('RHODESIA',1)
INSERT INTO MARCAS (DESCRIPCION_MARCA,ACTIVO) VALUES ('MOGUL',1)
INSERT INTO MARCAS (DESCRIPCION_MARCA,ACTIVO) VALUES ('MILKA',1)
INSERT INTO MARCAS (DESCRIPCION_MARCA,ACTIVO) VALUES ('ROCKLETS',1)
INSERT INTO MARCAS (DESCRIPCION_MARCA,ACTIVO) VALUES ('GUAYMALLEN',1)
INSERT INTO MARCAS (DESCRIPCION_MARCA,ACTIVO) VALUES ('OREO',1)



--CATEGORIAS
INSERT INTO CATEGORIAS (DESCRIPCION_CATEGORIA,ACTIVO) VALUES ('CHOCOLATES',1)
INSERT INTO CATEGORIAS (DESCRIPCION_CATEGORIA,ACTIVO) VALUES ('GOMITAS',1)
INSERT INTO CATEGORIAS (DESCRIPCION_CATEGORIA,ACTIVO) VALUES ('ALFAJORES',1)
INSERT INTO CATEGORIAS (DESCRIPCION_CATEGORIA,ACTIVO) VALUES ('BEBIDAS',1)
INSERT INTO CATEGORIAS (DESCRIPCION_CATEGORIA,ACTIVO) VALUES ('CARAMELOS',1)

--LOCALIDADES
--INSERT INTO LOCALIDADES (CODIGO_POSTAL,LOCALIDADES) VALUES (1620,'Flores')
--INSERT INTO LOCALIDADES (CODIGO_POSTAL,LOCALIDADES) VALUES (1621,'Palermo')
--INSERT INTO LOCALIDADES (CODIGO_POSTAL,LOCALIDADES) VALUES (1622,'Ciudadela')

--PROVEEDORES
--SELECT * FROM PROVEEDORES
INSERT INTO PROVEEDORES (CUIT,NOMBRE_PROVEEDOR,TELEFONO,MAIL,DIRECCION,ACTIVO) 
VALUES ('2050309453','SUPERGOMITAS SRL','1150602232','contacto@supergomitas.com','Centenario 126',1)
INSERT INTO PROVEEDORES (CUIT,NOMBRE_PROVEEDOR,TELEFONO,MAIL,DIRECCION,ACTIVO) 
VALUES ('1565822321','MILKA SA','1185213546','contacto@milka.com','Lavalle 2456',1)
INSERT INTO PROVEEDORES (CUIT,NOMBRE_PROVEEDOR,TELEFONO,MAIL,DIRECCION,ACTIVO) 
VALUES ('2213236255','ARCOR','1144203220','hola@arcor.com','Av Siempreviva 123',1)

--CLIENTES
INSERT INTO CLIENTES (DNI,APELLIDO,NOMBRE,TELEFONO,MAIL,DIRECCION,ACTIVO) 
VALUES ('40206350','CASTAÑO','MARCELO','1150327888','marcelocastaño@outlook.com','Av Falcon 652',1)
INSERT INTO CLIENTES (DNI,APELLIDO,NOMBRE,TELEFONO,MAIL,DIRECCION,ACTIVO) 
VALUES ('32875989','GOMEZ','YESICA','348474777','yesicagomez@outlook.com','Pringles 1225',1)
INSERT INTO CLIENTES (DNI,APELLIDO,NOMBRE,TELEFONO,MAIL,DIRECCION,ACTIVO) 
VALUES ('40889566','DIAZ','MONICA','1130057599','monidiaz@gmail.com','Colon 442',1)
INSERT INTO CLIENTES (DNI,APELLIDO,NOMBRE,TELEFONO,MAIL,DIRECCION,ACTIVO) 
VALUES ('25192577','SANCHEZ','ALBERTO','1140427364','','Libertad 3298',1)
INSERT INTO CLIENTES (DNI,APELLIDO,NOMBRE,TELEFONO,MAIL,DIRECCION,ACTIVO) 
VALUES ('36542564','GALLARDO','ALEX','1187980011','soyalex@gmail.com','Lamberti 987',1)

--USUARIOS
INSERT INTO USUARIOS(NOMBRE,CONTRASEÑA,TIPO_USUARIO,ACTIVO) 
VALUES ('EZEQUIEL','1996','VENDEDOR',1)
INSERT INTO USUARIOS(NOMBRE,CONTRASEÑA,TIPO_USUARIO,ACTIVO) 
VALUES ('ADMIN','PROGRAMACION','ADMIN',1)

--PRODUCTOS
INSERT INTO PRODUCTOS 
(CODIGO,NOMBRE,IDMARCA,IDCATEGORIA,CUITPROVEEDOR,PRECIO,STOCK_ACTUAL,STOCK_MINIMO,PORCENTAJE_GAN,ACTIVO) 
VALUES ('1274','Guaymallen de Chocolate', 2, 3, '1565822321',50,110,40,45,1)

INSERT INTO PRODUCTOS (CODIGO,NOMBRE,IDMARCA,IDCATEGORIA,CUITPROVEEDOR,PRECIO,STOCK_ACTUAL,STOCK_MINIMO,PORCENTAJE_GAN,ACTIVO) 
VALUES ('1275', 'Rocklets 50 G', 5, 1, '2213236255', 90,62,40,25,1)

INSERT INTO PRODUCTOS (CODIGO,NOMBRE,IDMARCA,IDCATEGORIA,CUITPROVEEDOR,PRECIO,STOCK_ACTUAL,STOCK_MINIMO,PORCENTAJE_GAN,ACTIVO) 
VALUES ('1276', 'Bon o Bon', 5, 1, '2213236255', 42,120,80,20,1)

INSERT INTO PRODUCTOS (CODIGO,NOMBRE,IDMARCA,IDCATEGORIA,CUITPROVEEDOR,PRECIO,STOCK_ACTUAL,STOCK_MINIMO,PORCENTAJE_GAN,ACTIVO) 
VALUES ('1277', 'Gomitas Mogul', 3, 2, '205030945311', 60, 95, 32, 29,1)

--COMPRAS


--VENTAS